import { Chain } from '@omniwallet/utils';

export const CHAINS: Record<string, Chain> = {
  ethereum: {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    decimals: 18,
    rpcUrl: process.env.ETHEREUM_RPC_URL || 'https://eth.llamarpc.com',
    explorerUrl: 'https://etherscan.io',
    logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    chainIdHex: '0x1',
    isEVM: true,
  },
  polygon: {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'MATIC',
    decimals: 18,
    rpcUrl: process.env.POLYGON_RPC_URL || 'https://polygon.llamarpc.com',
    explorerUrl: 'https://polygonscan.com',
    logoUrl: 'https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png',
    chainIdHex: '0x89',
    isEVM: true,
  },
  bsc: {
    id: 'bsc',
    name: 'BNB Chain',
    symbol: 'BNB',
    decimals: 18,
    rpcUrl: process.env.BSC_RPC_URL || 'https://bsc-dataseed.binance.org',
    explorerUrl: 'https://bscscan.com',
    logoUrl: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
    chainIdHex: '0x38',
    isEVM: true,
  },
  arbitrum: {
    id: 'arbitrum',
    name: 'Arbitrum One',
    symbol: 'ETH',
    decimals: 18,
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io',
    logoUrl: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg',
    chainIdHex: '0xa4b1',
    isEVM: true,
  },
  solana: {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    decimals: 9,
    rpcUrl: process.env.SOLANA_RPC_URL || 'https://api.mainnet-beta.solana.com',
    explorerUrl: 'https://solscan.io',
    logoUrl: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
    isEVM: false,
  },
  bitcoin: {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    decimals: 8,
    rpcUrl: process.env.BITCOIN_RPC_URL || 'https://blockstream.info/api',
    explorerUrl: 'https://blockstream.info',
    logoUrl: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    isEVM: false,
  },
};

export const EVM_CHAINS = Object.values(CHAINS).filter((c) => c.isEVM);
